add_library(qindaqt_window_management STATIC src/command_codec.cpp src/geometry.cpp src/controller.cpp)
add_library(QindaQt::WindowManagement ALIAS qindaqt_window_management)
target_sources(qindaqt_window_management PUBLIC FILE_SET public_headers TYPE HEADERS BASE_DIRS include FILES include/qindaqt/window_management/command.h include/qindaqt/window_management/controller.h)
target_include_directories(qindaqt_window_management PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include> $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(qindaqt_window_management PUBLIC Qt6::Core)
set_target_properties(qindaqt_window_management PROPERTIES POSITION_INDEPENDENT_CODE ON EXPORT_NAME WindowManagement)
target_compile_features(qindaqt_window_management PUBLIC cxx_std_20)
qindaqt_enable_warnings(qindaqt_window_management)
install(TARGETS qindaqt_window_management EXPORT QindaQtTargets FILE_SET public_headers DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
