// SPDX-License-Identifier: GPL-3.0-or-later
import QindaQt.Shell.GlobalMenu as GlobalMenuComponents
import QtQuick
import QtQuick.Controls
import QtTest

// Top-level menu switching contract: with one entry's menu open, the menu bar
// must follow the pointer — clicking another entry switches the popup to that
// entry's menu, clicking the open entry closes it, and hovering another entry
// switches while a menu is open. Production runs the popup as a separate
// window whose native close paths (press-outside, focus loss) race the
// switch; these rows pin the outcome rather than the mechanism.
Item {
    id: root
    width: 640
    height: 400

    property var theme: ({
        "colors": {
            "text": "#f2f1eb", "textMuted": "#a9afa4",
            "surfaceRaised": "#2c312e", "border": "#3c433f",
            "accent": "#8fc8b7", "accentText": "#10201b"
        },
        "cornerRadius": 6
    })

    QtObject {
        id: fakeAccess
        property bool available: true
        property var items: []
        property int activateCalls: 0
        function activate(id) { ++activateCalls }
    }

    GlobalMenuComponents.GlobalMenuApplet {
        id: applet
        anchors.top: parent.top
        width: 420
        height: 40
        access: fakeAccess
        theme: root.theme
    }

    TestCase {
        name: "GlobalMenuAppletSwitch"
        when: windowShown

        function menuItems() {
            return [{
                "id": "file", "kind": "submenu", "text": "File",
                "enabled": true, "children": [{
                    "id": "new", "kind": "action", "text": "New",
                    "enabled": true
                }]
            }, {
                "id": "edit", "kind": "submenu", "text": "Edit",
                "enabled": true, "children": [{
                    "id": "undo", "kind": "action", "text": "Undo",
                    "enabled": true
                }]
            }]
        }

        function init() {
            fakeAccess.items = menuItems()
            fakeAccess.activateCalls = 0
            const p = findChild(applet, "globalMenuPopup")
            if (p !== null) {
                if (p.opened)
                    p.close()
                // Keep the toggle-suppression window from leaking across
                // test boundaries.
                p.closedAnchorItem = null
                p.closedAt = 0
            }
        }

        function cleanup() {
            const popup = findChild(applet, "globalMenuPopup")
            if (popup !== null && popup.opened)
                popup.close()
        }

        function entries() {
            const row = findChild(applet, "globalMenuHorizontalLayout")
            verify(row !== null)
            const list = row.children.filter(
                child => child.objectName === "globalMenuTopLevelItem")
            // Freshly created delegates overlap at the origin until the Row
            // positions them; clicks must target settled geometry.
            tryVerify(function() {
                return list.length === 2 && list[0].width > 0
                    && list[1].x > list[0].x + list[0].width - 1
            })
            return list
        }

        function popup() {
            const popup = findChild(applet, "globalMenuPopup")
            verify(popup !== null)
            return popup
        }

        function clickEntry(entry) {
            mouseClick(entry, entry.width / 2, entry.height / 2)
        }

        // qmltestrunner's first mouseMove only positions the cursor; hover
        // enter is generated by a subsequent move. Warp to a neutral spot
        // first so the target move is a real hover transition.
        function hoverEntry(entry) {
            mouseMove(root, 2, root.height - 2)
            mouseMove(entry, entry.width / 2, entry.height / 2)
        }

        function verifyOpenMenu(text, entry) {
            const p = popup()
            tryCompare(p, "opened", true)
            tryVerify(function() { return String(p.currentMenu.text ?? "") === text })
            compare(p.anchorItem, entry)
        }

        function test_clickOtherEntrySwitchesMenu() {
            const list = entries()
            compare(list.length, 2)
            clickEntry(list[1])
            verifyOpenMenu("Edit", list[1])
            clickEntry(list[0])
            verifyOpenMenu("File", list[0])
        }

        function test_clickOpenEntryClosesIt() {
            const list = entries()
            clickEntry(list[0])
            verifyOpenMenu("File", list[0])
            clickEntry(list[0])
            tryCompare(popup(), "opened", false)
        }

        function test_entryReopensAfterToggleSettles() {
            // The toggle suppression is bounded to the closing click gesture;
            // a later click opens the menu again.
            const list = entries()
            clickEntry(list[0])
            verifyOpenMenu("File", list[0])
            clickEntry(list[0])
            tryCompare(popup(), "opened", false)
            wait(500)
            clickEntry(list[0])
            verifyOpenMenu("File", list[0])
        }

        function test_hoverSwitchesMenuWhileOpen() {
            const list = entries()
            clickEntry(list[1])
            verifyOpenMenu("Edit", list[1])
            hoverEntry(list[0])
            tryVerify(function() {
                return popup().opened
                    && String(popup().currentMenu.text ?? "") === "File"
            })
            compare(popup().anchorItem, list[0])
        }

        function test_hoverDoesNotOpenWhenClosed() {
            const list = entries()
            hoverEntry(list[0])
            verify(list[0].hovered)
            compare(popup().opened, false)
        }
    }
}
