# SPDX-License-Identifier: GPL-3.0-or-later
"""Prove qindaqt-wm's windowed backend against an isolated Weston parent."""

from __future__ import annotations

import argparse
import json
import os
import stat
import subprocess
import sys
import tempfile
import time
from pathlib import Path

# AGENT-GUARD: Keep integration runs from depositing generated bytecode beside
# source files; runtime artifacts belong under the isolated or build tree.
sys.dont_write_bytecode = True

from test_nested_session import (
    ScenarioCoverageError,
    extract_probe_result,
    isolated_environment,
    load_virtual_spec,
    validate_probe_result,
)


PARENT_SOCKET = "qindaqt-weston-parent"


def wait_for_wayland_socket(process: subprocess.Popen[bytes], path: Path) -> None:
    deadline = time.monotonic() + 5
    while time.monotonic() < deadline:
        if path.exists() and stat.S_ISSOCK(path.stat().st_mode):
            return
        return_code = process.poll()
        if return_code is not None:
            raise RuntimeError(f"Weston exited before publishing its socket (code {return_code})")
        time.sleep(0.05)
    raise RuntimeError(f"Weston did not publish {path} within 5 seconds")


def run_inside_dbus(arguments: argparse.Namespace) -> int:
    try:
        spec = load_virtual_spec(arguments.scenario)
    except ScenarioCoverageError as error:
        print(f"scenario is not representable: {error}", file=sys.stderr)
        return 2
    if spec.output_count != 1:
        print("parent-Wayland proof currently requires one enabled output", file=sys.stderr)
        return 2

    runtime = Path(os.environ["XDG_RUNTIME_DIR"])
    state = Path(os.environ["XDG_STATE_HOME"])
    weston_log = state / "weston.log"
    weston_command = [
        arguments.weston,
        "--backend=headless",
        "--renderer=pixman",
        "--no-config",
        f"--socket={PARENT_SOCKET}",
        "--idle-time=0",
        f"--width={spec.pixel_width}",
        f"--height={spec.pixel_height}",
        "--scale=1",
        "--fake-seat",
        f"--log={weston_log}",
    ]
    weston = subprocess.Popen(
        weston_command,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    try:
        wait_for_wayland_socket(weston, runtime / PARENT_SOCKET)
        environment = dict(os.environ)
        environment["WAYLAND_DISPLAY"] = PARENT_SOCKET
        completed = subprocess.run(
            [
                arguments.launcher,
                "--plugin-root",
                str(arguments.plugin_root),
                "--windowed",
                "--width",
                str(spec.logical_width),
                "--height",
                str(spec.logical_height),
                "--scale",
                f"{spec.scale:.12g}",
                "--output-count",
                "1",
                "--test-scenario",
                str(arguments.scenario),
                "--no-lockscreen",
                "--no-global-shortcuts",
                "--session",
                arguments.probe,
            ],
            env=environment,
            text=True,
            capture_output=True,
            timeout=20,
            check=False,
        )
    except (OSError, RuntimeError, subprocess.TimeoutExpired) as error:
        print(f"parent-Wayland launch failed: {error}", file=sys.stderr)
        if weston_log.is_file():
            print(weston_log.read_text(encoding="utf-8", errors="replace"), file=sys.stderr)
        return 1
    finally:
        weston.terminate()
        try:
            weston.wait(timeout=3)
        except subprocess.TimeoutExpired:
            weston.kill()
            weston.wait(timeout=3)

    if completed.returncode != 0:
        print(completed.stdout, file=sys.stderr)
        print(completed.stderr, file=sys.stderr)
        return completed.returncode or 1
    try:
        result = extract_probe_result(completed.stdout)
        validate_probe_result(
            result,
            spec,
            inspect_compositor_outputs=False,
            expect_workflow=False,
        )
    except (RuntimeError, json.JSONDecodeError) as error:
        print(f"parent-Wayland validation failed: {error}", file=sys.stderr)
        print(completed.stdout, file=sys.stderr)
        return 1
    result["scenarioCoverage"] = spec.coverage
    result["parentWaylandProof"] = {
        "parent": "Weston",
        "parentBackend": "headless",
        "qindaqtBackend": "windowed",
        "drmTested": False,
    }
    print(json.dumps(result, sort_keys=True))
    return 0


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("launcher")
    parser.add_argument("probe")
    parser.add_argument("dbus_runner")
    parser.add_argument("weston")
    parser.add_argument("scenario", type=Path)
    parser.add_argument("--plugin-root", type=Path, required=True)
    parser.add_argument("--inside-dbus", action="store_true", help=argparse.SUPPRESS)
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    if arguments.inside_dbus:
        return run_inside_dbus(arguments)
    with tempfile.TemporaryDirectory(prefix="qindaqt-parent-wayland-test-") as directory:
        environment = isolated_environment(Path(directory))
        command = [
            arguments.dbus_runner,
            "--",
            sys.executable,
            str(Path(__file__).resolve()),
            arguments.launcher,
            arguments.probe,
            arguments.dbus_runner,
            arguments.weston,
            str(arguments.scenario),
            "--plugin-root",
            str(arguments.plugin_root),
            "--inside-dbus",
        ]
        completed = subprocess.run(
            command,
            env=environment,
            text=True,
            capture_output=True,
            timeout=30,
            check=False,
        )
    if completed.stdout:
        print(completed.stdout, end="")
    if completed.returncode != 0 and completed.stderr:
        print(completed.stderr, end="", file=sys.stderr)
    return completed.returncode


if __name__ == "__main__":
    raise SystemExit(main())
