foreach(behavior IN ITEMS geometry_codec context_controller)
    add_executable(qindaqt_window_management_${behavior}_tests tst_${behavior}.cpp)
    target_link_libraries(qindaqt_window_management_${behavior}_tests PRIVATE QindaQt::WindowManagement Qt6::Test)
    target_compile_features(qindaqt_window_management_${behavior}_tests PRIVATE cxx_std_20)
    qindaqt_enable_warnings(qindaqt_window_management_${behavior}_tests)
    add_test(NAME qindaqt.window-management-${behavior} COMMAND qindaqt_window_management_${behavior}_tests)
endforeach()
