# SPDX-License-Identifier: GPL-3.0-or-later
if(NOT DEFINED SOURCE_ROOT)
    message(FATAL_ERROR "SOURCE_ROOT required")
endif()
set(root "${SOURCE_ROOT}/src/services/bluetooth_radio_helper")
file(READ "${root}/data/qindaqt-bluetooth-radio-helper.service.in" unit)
foreach(required IN ITEMS "PrivateUsers=yes" "PrivateDevices=yes" "NoNewPrivileges=yes"
    "BindPaths=/dev/rfkill" "DevicePolicy=closed" "DeviceAllow=/dev/rfkill rw"
    "ProtectSystem=strict" "ProtectHome=yes" "RestrictAddressFamilies=AF_UNIX" "Restart=no")
    string(FIND "${unit}" "${required}" found)
    if(found LESS 0)
        message(FATAL_ERROR "Radio helper lost sandbox requirement: ${required}")
    endif()
endforeach()
file(READ "${root}/data/org.qindaqt.BluetoothRadio1.service.in" activation)
if(NOT activation MATCHES "Exec=/usr/bin/false")
    message(FATAL_ERROR "Radio helper must not bypass its unit through direct D-Bus Exec")
endif()
file(READ "${root}/src/radio_platform_linux.cpp" platform)
if(platform MATCHES "event.op = RFKILL_OP_CHANGE_ALL"
    OR platform MATCHES "RFKILL_OP_DEL;|RFKILL_OP_ADD;")
    message(FATAL_ERROR "Radio helper added a non-selected write")
endif()
if(NOT platform MATCHES "event.idx = m_index;" OR NOT platform MATCHES "event.op = RFKILL_OP_CHANGE;")
    message(FATAL_ERROR "Selected-index write contract missing")
endif()
file(GLOB_RECURSE public_headers "${root}/include/*.h")
foreach(header IN LISTS public_headers)
    file(READ "${header}" content)
    if(content MATCHES "linux/rfkill|radio_platform_p|radio_operation_p|/dev/rfkill|sys/stat")
        message(FATAL_ERROR "Radio public boundary leaks platform authority")
    endif()
endforeach()
message(STATUS "Optional selected-radio helper keeps sandbox and public boundaries")
