# SPDX-License-Identifier: GPL-3.0-or-later
find_program(DBUS_DAEMON_EXECUTABLE dbus-daemon REQUIRED)
foreach(test IN ITEMS resident_lock_service qt_native_lock_request)
 qt_add_executable(qindaqt_${test}_tests tst_${test}.cpp private_bus.h)
 target_link_libraries(qindaqt_${test}_tests PRIVATE QindaQt::NativeLockService QindaQt::CompositorNames Qt6::Test)
 target_compile_definitions(qindaqt_${test}_tests PRIVATE QINDAQT_DBUS_DAEMON_EXECUTABLE="${DBUS_DAEMON_EXECUTABLE}")
 qindaqt_enable_warnings(qindaqt_${test}_tests)
 add_test(NAME qindaqt.${test} COMMAND qindaqt_${test}_tests)
 set_tests_properties(qindaqt.${test} PROPERTIES TIMEOUT 30 LABELS "service;dbus")
endforeach()
