[Icon Theme]
Name=QindaQt
Comment=Rounded QindaPunk geometry for QindaQt
Inherits=hicolor
Directories=scalable/apps,scalable/actions,scalable/devices,scalable/places,scalable/mimetypes,scalable/categories,scalable/status

[scalable/apps]
Context=Applications
Size=64
Type=Scalable
MinSize=16
MaxSize=256

[scalable/actions]
Context=Actions
Size=64
Type=Scalable
MinSize=16
MaxSize=256

[scalable/devices]
Context=Devices
Size=64
Type=Scalable
MinSize=16
MaxSize=256

[scalable/places]
Context=Places
Size=64
Type=Scalable
MinSize=16
MaxSize=256

[scalable/mimetypes]
Context=MimeTypes
Size=64
Type=Scalable
MinSize=16
MaxSize=256

[scalable/categories]
Context=Categories
Size=64
Type=Scalable
MinSize=16
MaxSize=256

[scalable/status]
Context=Status
Size=64
Type=Scalable
MinSize=16
MaxSize=256
